# Generated by Django 2.1.7 on 2019-03-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('courses', '0002_auto_20190320_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdata',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='classdata',
            name='enrollment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='enrollments.Enrollments'),
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='grantEnrollment',
        ),
        migrations.AddField(
            model_name='classdata',
            name='grantEnrollment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='enrollments.GrantEnrollmentData'),
        ),
    ]
