# Generated by Django 2.1.7 on 2019-03-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdata',
            name='enrollment',
            field=models.ManyToManyField(to='enrollments.Enrollments'),
        ),
        migrations.AddField(
            model_name='classdata',
            name='grantEnrollment',
            field=models.ManyToManyField(to='enrollments.GrantEnrollmentData'),
        ),
    ]
