# Generated by Django 2.1.7 on 2019-04-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190320_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classdata',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='classdata',
            name='grantEnrollment',
        ),
    ]
